lib/cms_web/router.ex
defmodule CmsWeb.Router do
  use CmsWeb, :router

  alias Cms.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plug.Authentication
  end

  pipeline :authenticated do
    plug Plug.EnsureAuthentication
    plug Plug.ShowSidebar
  end

  scope "/admin", CmsWeb, as: :admin do
    pipe_through [:browser, :authenticated]
    get "/", Admin.HomeController, :index
    resources("/post", Admin.PostController) do
      get "/publish", Admin.PostController, :publish, as: :publish
    end
  end

  scope "/", CmsWeb do
    pipe_through :browser
    resources("/", PageController, only: [:index, :show])
    resources("/session", SessionController, only: [:create, :new, :delete])
  end

end

lib/cms_web/views/layout_view.ex
defmodule CmsWeb.LayoutView do
  use CmsWeb, :view
end

lib/cms_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Fake news">
    <meta name="author" content="Martijn Meeldijk & Tim Vanherwegen">

    <title>The Today Express</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/style.css") %>">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,700" rel="stylesheet">
  </head>

  <body>
    <%= render "navbar.html", conn: @conn %>
    <div class="container-fluid">
    
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= if Map.has_key?(@conn.assigns, :sidebar) do %>
          <%= render "sidebar.html", conn: @conn %>
          <div class="main">
            <%= render @view_module, @view_template, assigns %>
          </div>
        <% else %>
        <%= render @view_module, @view_template, assigns %>
        <% end %>
      </main>

    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/cms_web/templates/layout/navbar.html.eex
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="/images/locomotive.png" class="img img-fluid" style="height: 1.6rem">
      
      The Today Express
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">

        <li class="nav-item">
          <%= link("Home", to: page_path(@conn, :index), class: "nav-link") %>
        </li>

        <li class="nav-item">
        <%= if Cms.Auth.Accounts.is_current_user_admin?(@conn) do %>
          <%= link("Dashboard", to: admin_home_path(@conn, :index), class: "nav-link") %>
        <% end %>
        </li>

        <li class="nav-item">
        <%= if Cms.Auth.Accounts.get_current_user(@conn) do %>
          <%= link("Logout", to: session_path(@conn, :new), method: :delete, class: "nav-link") %>
        <% else %>
          <%= link("Login", to: session_path(@conn, :new), class: "nav-link") %>
        <% end %>
        </li>

      </ul>
    </div>
  </div>
</nav>

lib/cms_web/templates/layout/sidebar.html.eex
<div class="sidenav bg-dark">
  <%= link raw(~s'<i class="fa fa-tachometer"></i>Dashboard'), to: admin_home_path(@conn, :index) %>
  <%= link raw(~s'<i class="fa fa-paper-plane"></i>Posts'), to: admin_post_path(@conn, :index) %>
</div>